FROM python:3.9-alpine

COPY . /app

WORKDIR /app

RUN apk update
RUN apk add bash
RUN apk add poetry
RUN apk add git
RUN apk add --update build-base linux-headers python3-dev py-psutil && rm -rf /var/cache/apk/*
RUN apk add nano
RUN apk add make
RUN poetry config virtualenvs.in-project true

ENTRYPOINT ["/bin/bash"]